### ISSUE TITLE
Funny sorting

### ISSUE THREAD

**Issue by Alex-Just** [Alexxx666/to-do-list#2]
<img width="229" alt="screen shot 2016-12-11 at 22 36 16" src="https://cloud.githubusercontent.com/assets/4204525/21082717/69034efa-bff2-11e6-8a71-d4f37d7dc0a5.png">
<img width="235" alt="screen shot 2016-12-11 at 22 36 10" src="https://cloud.githubusercontent.com/assets/4204525/21082718/6920e91a-bff2-11e6-9965-bce71ff8abaf.png">

**Comment by Alex-Just** [comment]
<img width="219" alt="screen shot 2016-12-11 at 22 41 10" src="https://cloud.githubusercontent.com/assets/4204525/21082755/f703f376-bff2-11e6-80b6-fb4e448b2adb.png">
<img width="223" alt="screen shot 2016-12-11 at 22 40 53" src="https://cloud.githubusercontent.com/assets/4204525/21082756/f71d40ce-bff2-11e6-9aab-52e51a27c0e4.png">

**Comment by Alexxx666** [comment]
It is not a bug, it is a feature - it sorts in reverse order according to the time of task addition.
In description: "Sort tasks in reverse order by clicking on the title"
